services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    command: go run cmd/main.go
    ports:
      - "8080:8080"
    environment:
      - LOCATION_SERVICE_URL=http://ip-api.com/json/
      - WEATHER_SERVICE_URL=http://wttr.in/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
